### ISSUE TITLE
Do you have AMISCE tool ?

### ISSUE THREAD

**Issue by LeRatierBretonnien** [RomanHargrave/amifldrv#2]
Hi, very good job, i am now able to read/write BIOS from Linux. But i  would like also to save BIOS settings and restore them to other servers. Hence i need the AMISCE tool (Aptio 5)  for Linux.
Do you have this somewhere ?

**Comment by RomanHargrave** [comment]
Unfortunately, no. But given AMI's incredibly poor access control for their "secret" software, you should be able to find it easily. I'll take a quick look and see if I can find it anywhere.

**Comment by RomanHargrave** [comment]
Unfortunately, I was not able to _quickly and dirtily_ find an Aptio V version of amisce.

I do suggest looking, especially on Chinese PC modding forums, since that's where a lot of the original leaks are from.

**Comment by krasny2k5** [comment]
I'll leave this link to gigabyte server here:

http://download.gigabyte.us/FileList/Utility/server_utility_command_line_utility_2.0.zip

**Comment by RomanHargrave** [comment]
i'll rehost that eventually

**Comment by psyborg55** [comment]
it is available in this HP linux iso: https://support.hpe.com/hpsc/swd/public/detail?swItemId=MTX-f341059d222f4038a994ebd48a
