### ISSUE TITLE
Need compile instructions

### ISSUE THREAD

**Issue by penguinjeff** [RomanHargrave/amifldrv#4]
tried "make"
~/github/RomanHargrave/amifldrv# make
make -C /lib/modules/6.6.6-200.fc39.x86_64/build SUBDIRS=/root/github/RomanHargrave/amifldrv modules
make[1]: Entering directory '/root/rpmbuild/BUILD/kernel-6.6.6/linux-6.6.6-200.fc39.x86_64'
  CALL    scripts/checksyscalls.sh
  DESCEND objtool
make[5]: 'install_headers' is up to date.
  DESCEND bpf/resolve_btfids
make[5]: 'install_headers' is up to date.
  CHK     kernel/kheaders_data.tar.xz
make[1]: Leaving directory '/root/rpmbuild/BUILD/kernel-6.6.6/linux-6.6.6-200.fc39.x86_64'
rm -f amifldrv.o_shipped
mv amifldrv.o amifldrv.o_shipped
mv: cannot stat 'amifldrv.o': No such file or directory
make: *** [Makefile:10: default] Error 1

~/github/RomanHargrave/amifldrv# make amifldrv.o
cc    -c -o amifldrv.o amifldrv.c
amifldrv.c:6:10: fatal error: asm/io.h: No such file or directory
    6 | #include <asm/io.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [<builtin>: amifldrv.o] Error 1

**Comment by RomanHargrave** [comment]
Hey there, while I posted these some time ago, they are a snapshot of what AMI was using at the time. I don't know that this will work with newer AMI boards, and if it does I do not know that it necessarily works with today's 5/6 kernels. [There are some forks](https://github.com/partcyborg/amifldrv) that were made to work with Linux 5, but I can't comment on whether they work either.
